server:
  port: 8082
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s  # shutdown 대기 시간
  profiles:
    group:
      local:
        common-local

      stage:
        common-local

      prod:
    active: local
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
