spring:
  kafka:
    producer:
      bootstrap-servers: "localhost:9092"
    consumer:
      bootstrap-servers: "localhost:9092"

cors:
  allowedOrigins: http://localhost:3000

token:
  secretKey: "dsakljqd1idj8qwjddj12idjdsakljqd1idj8qwjddj12idjdsakljqd1idj8qwjddj12idjdsakljqd1idj8qwjddj12idjdsakljqd1idj8qwjddj12idj"
  accessTokenExpirationMillis: 2000000
