spring:
  kafka:
    producer:
      bootstrap-servers: "localhost:49092"
    consumer:
      bootstrap-servers: "localhost:49092"

token:
  secretKey: "dsakljqd1idj8qwjddj12idjdsakljqd1idj8qwjddj12idjdsakljqd1idj8qwjddj12idjdsakljqd1idj8qwjddj12idjdsakljqd1idj8qwjddj12idj"
  accessTokenExpirationMillis: 2000000
