spring:
  kafka:
    producer:
      bootstrap-servers: "localhost:9092"
    consumer:
      bootstrap-servers: "localhost:9092"
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0

token:
  secretKey: "dsakljqd1idj8qwjddj12idjdsakljqd1idj8qwjddj12idjdsakljqd1idj8qwjddj12idjdsakljqd1idj8qwjddj12idjdsakljqd1idj8qwjddj12idj"
  accessTokenExpirationMillis: 2000000000
