spring:
  kafka:
    producer:
      bootstrap-servers: "localhost:49092"
    consumer:
      bootstrap-servers: "localhost:49092"
  flyway:
    enabled: false
    baseline-on-migrate: false
    baseline-version: 0

token:
  secretKey: "dsakljqd1idj8qwjddj12idjdsakljqd1idj8qwjddj12idjdsakljqd1idj8qwjddj12idjdsakljqd1idj8qwjddj12idjdsakljqd1idj8qwjddj12idj"
  accessTokenExpirationMillis: 2000000
