server:
  port: 8080
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s  # shutdown 대기 시간
  profiles:
    group:
      local:
        common-local

      stage:
        common-local

      prod:
    active: local

mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
