spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true

    hibernate:
      ddl-auto: create

  kafka:
    consumer:
      group-id: "cupid-group"

cors:
  allowedOrigins: http://localhost:3000

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE


token:
  secretKey: "sssssssssssssssssssssssssssssssss"
  accessTokenExpirationMillis: 2000000
