server:
  port: 8080

spring:
  profiles:
    group:
      local:
        common-local

      stage:

      prod:
    active: local

mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
